### ISSUE TITLE
Double Free in img2sixel

### ISSUE THREAD

**Issue by randomssr** [libsixel/libsixel#65]
When the command containts `-B#354 -B-` argument, the program will appear double free.

In sixel_encoder_setopt(), libsixel parse command line options to parse the option "B". However, libsixel frees encoder->bgcolor, but not malloc encoder->bgcolor in sixel_parse_x_colorspec(), and continue to free encoder->bgcolor in sixel_encoder_unref().
```
case SIXEL_OPTFLAG_BGCOLOR:  /* B */
    /* parse --bgcolor option */
    if (encoder->bgcolor) {
        sixel_allocator_free(encoder->allocator, encoder->bgcolor);
    }
    status = sixel_parse_x_colorspec(&encoder->bgcolor,
                                     value,
                                     encoder->allocator);
    if (SIXEL_FAILED(status)) {
        sixel_helper_set_additional_message(
            "cannot parse bgcolor option.");
        status = SIXEL_BAD_ARGUMENT;
        goto end;
    }
    break;
```

### Test Environment
Ubuntu 20.04, 64 bit
libsixel (master, [`e2c4937`](https://github.com/libsixel/libsixel/commit/master))

### How to trigger
1. Compile the program with AddressSanitizer
2. Run command `$ img2sixel -B#354 -B-`

#### ASAN report
```
$ ./img2sixel -B#354 -B-
usage: img2sixel [-78eIkiugvSPDOVH] [-p colors] [-m file] [-d diffusiontype]
                 [-f findtype] [-s selecttype] [-c geometory] [-w width]
                 [-h height] [-r resamplingtype] [-q quality] [-l loopmode]
                 [-t palettetype] [-n macronumber] [-C score] [-b palette]
                 [-E encodepolicy] [-B bgcolor] [-o outfile] [filename ...]
for more details, type: 'img2sixel -H'.
runtime error: bad argument detected
cannot parse bgcolor option.
=================================================================
==2864772==ERROR: AddressSanitizer: attempting double-free on 0x602000000030 in thread T0:
    #0 0x7f54397e81c7 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:123
    #1 0x7f5439710e46 in sixel_encoder_unref (/lib/x86_64-linux-gnu/libsixel.so.1+0x3de46)
    #2 0x555e66f68c14 in main ../converters/img2sixel.c:458
    #3 0x7f5439505082 in __libc_start_main ../csu/libc-start.c:308
    #4 0x555e66f6634d in _start (/home/cmd/ofuzz/bug_report/libsixel/img2sixel/crash/img2sixel+0x234d)

0x602000000030 is located 0 bytes inside of 3-byte region [0x602000000030,0x602000000033)
freed by thread T0 here:
    #0 0x7f54397e81c7 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:123
    #1 0x7f5439711227 in sixel_encoder_setopt (/lib/x86_64-linux-gnu/libsixel.so.1+0x3e227)

previously allocated by thread T0 here:
    #0 0x7f54397e8527 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f54397109a4  (/lib/x86_64-linux-gnu/libsixel.so.1+0x3d9a4)

SUMMARY: AddressSanitizer: double-free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:123 in __interceptor_free
==2864772==ABORTING
```

**Comment by randomssr** [comment]
Hello, @ctrlcctrlv , thanks for your verifivation.
I still have a question. Can I request a CVE with this bug?

**Comment by ctrlcctrlv** [comment]
@randomssr Sorry, I've never done that and don't know how that process works. If I were you I wouldn't, because this bug assumes applications that send uncontrolled user input to argv of a utility and not the core library, so likely affects almost no real world application, but ultimately that's not my decision. :-)

**Comment by randomssr** [comment]
@ctrlcctrlv  Thanks for your answer.
